[package]
name = "ftch"
version = "0.2.0"
edition = "2024"
authors = [ "sophsystems" ]
description = "A fast, tiny system fetch utility."
repository = "https://github.com/Sophed/ftch"
license = "MIT"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
